# 다음을 테마로 적용해 본다 - 1. 
#
#[theme]
#primaryColor= "white"
#backgroundColor= "#444D51"
#secondaryBackgroundColor= "red"
#textColor= "white"
#font= "sans serif"

# 다음을 테마로 적용해 본다 - 2. 
#
#[theme]
#primaryColor="white"
# backgroundColor="#6EC531"
# secondaryBackgroundColor="#F1D651"
# textColor="#856256"
# font="sans serif"

# 다음을 테마로 적용해 본다 - 3. 
#
#[theme]
# base="dark"   또는  "light"

# HEX 컬러는 다음 사이트를 참고해 본다.
# https://www.color-name.com/
